Update README for python 3
decode_responses=True is required on python 3 to avoid failures like:

```
  File "/home/macobo/projects/misc/tasktiger/tasktiger/__init__.py", line 335, in run_worker
    tiger.run_worker(**kwargs)
  File "/home/macobo/projects/misc/tasktiger/tasktiger/__init__.py", line 265, in run_worker
    worker.run()
  File "/home/macobo/projects/misc/tasktiger/tasktiger/worker.py", line 711, in run
    self.connection.smembers(self._key(QUEUED))))
  File "/home/macobo/projects/misc/tasktiger/tasktiger/worker.py", line 99, in _filter_queues
    return [q for q in queues if match(q)]
  File "/home/macobo/projects/misc/tasktiger/tasktiger/worker.py", line 99, in <listcomp>
    return [q for q in queues if match(q)]
  File "/home/macobo/projects/misc/tasktiger/tasktiger/worker.py", line 92, in match
    for part in reversed_dotted_parts(queue):
  File "/home/macobo/projects/misc/tasktiger/tasktiger/_internal.py", line 97, in reversed_dotted_parts
    idx = s.rfind('.', 0, idx)
TypeError: a bytes-like object is required, not 'str'
```